In [2]:
! pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\ahamg\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ahamg\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\ahamg\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 3.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.9 MB 4.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.9 MB 4.1 MB/s eta 0:00:02
   ---------------- ----------------------- 4.2/9.9 MB 5.2 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 5.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 5.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 5.7 MB/s  0:00:01
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.3 tzdata-2026.2

In [3]:
import pandas as pb

In [4]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago'],
    'Position': ['winner', 'first_runner_up', 'second_runner_up']
}
data

{'Name': ['Alice', 'Bob', 'Charlie'],
 'Age': [25, 30, 35],
 'City': ['New York', 'Los Angeles', 'Chicago'],
 'Position': ['winner', 'first_runner_up', 'second_runner_up']}

In [5]:
df = pb.DataFrame(data)
df

      Name  Age         City          Position
0    Alice   25     New York            winner
1      Bob   30  Los Angeles   first_runner_up
2  Charlie   35      Chicago  second_runner_up

In [6]:
df[['Name','Age']] ## selecting multiple columns from the dataframe

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [7]:
df

      Name  Age         City          Position
0    Alice   25     New York            winner
1      Bob   30  Los Angeles   first_runner_up
2  Charlie   35      Chicago  second_runner_up

In [8]:
df.loc[1] ## selecting a single row from the dataframe using loc

Name                    Bob
Age                      30
City            Los Angeles
Position    first_runner_up
Name: 1, dtype: object

In [9]:
df.iloc[1] ## selecting a single row from the dataframe using iloc, it will select the second row of the dataframe because iloc uses integer indexing, so it starts from 0

Name                    Bob
Age                      30
City            Los Angeles
Position    first_runner_up
Name: 1, dtype: object

In [10]:
df

      Name  Age         City          Position
0    Alice   25     New York            winner
1      Bob   30  Los Angeles   first_runner_up
2  Charlie   35      Chicago  second_runner_up

Setting individual column as a index

In [11]:
df.set_index('Position', inplace=True) ## setting the index of the dataframe to the 'Position' column, inplace=True will modify the original dataframe

In [12]:
df

                     Name  Age         City
Position
winner              Alice   25     New York
first_runner_up       Bob   30  Los Angeles
second_runner_up  Charlie   35      Chicago

In [13]:
df.index = ['winner','first_runner_up','second_runner_up'] ## setting the index of the dataframe to a list of values, it will replace the existing index with the new index

In [14]:
df

                     Name  Age         City
winner              Alice   25     New York
first_runner_up       Bob   30  Los Angeles
second_runner_up  Charlie   35      Chicago

In [15]:
df.iloc[1]  ## Position          ## selecting a single row from the dataframe using iloc, it will select the second row of the dataframe because iloc uses integer indexing, so it starts from 0

Name            Bob
Age              30
City    Los Angeles
Name: first_runner_up, dtype: object

In [16]:
df.loc['first_runner_up'] ## labels

Name            Bob
Age              30
City    Los Angeles
Name: first_runner_up, dtype: object

In [17]:
del df['City']

In [18]:
df

                     Name  Age
winner              Alice   25
first_runner_up       Bob   30
second_runner_up  Charlie   35

In [19]:
df.drop(['Age'], axis=1) ## dropping a column from the dataframe, axis=1 means we are dropping a column, inplace=True will modify the original dataframe

                     Name
winner              Alice
first_runner_up       Bob
second_runner_up  Charlie

In [20]:
df

                     Name  Age
winner              Alice   25
first_runner_up       Bob   30
second_runner_up  Charlie   35

In [21]:
new_column = {
    'Name':'NAME',
    'Age':'AGE'
}
df.rename(columns=new_column, inplace=True) ## renaming columns in the dataframe, inplace=True will modify the original dataframe

df

                     NAME  AGE
winner              Alice   25
first_runner_up       Bob   30
second_runner_up  Charlie   35

In [22]:
df['NAME_UPPER'] = df['NAME'].str.upper() ## converting the values in the 'NAME' column to uppercase using the str.upper() method

In [23]:
df

                     NAME  AGE NAME_UPPER
winner              Alice   25      ALICE
first_runner_up       Bob   30        BOB
second_runner_up  Charlie   35    CHARLIE

Performing Data Analysis Over Some Random Data

CSV Datafile

In [30]:
data = pb.read_csv('2_data.csv') ## reading a csv file into a dataframe using the read_csv() method
data

      Name    Age           City     Position
0    Alice      30      new york      Manager
1      Bob      25  Los Angeles     Developer
2  charlie      35       chicago      analyst
3     david     28       Houston     Designer
4       Eve     32       Phoenix   Consultant

Descriptive Analysis

In [31]:
data.info() ## Descriptive statistics of the dataframe, it will show the number of non-null values, data types and memory usage of the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      str
 1    Age      5 non-null      int64
 2    City     5 non-null      str
 3   Position  5 non-null      str
dtypes: int64(1), str(3)
memory usage: 292.0 bytes

Statistical Analysis

In [32]:
data.describe() ## Statistical summary of the dataframe, it will show the count, mean, std, min, 25%, 50%, 75% and max values of the numerical columns in the dataframe

            Age
count   5.000000
mean   30.000000
std     3.807887
min    25.000000
25%    28.000000
50%    30.000000
75%    32.000000
max    35.000000

In [33]:
data.head(2)

    Name    Age           City    Position
0  Alice      30      new york     Manager
1    Bob      25  Los Angeles    Developer

In [34]:
data.tail(2)

   Name    Age      City     Position
3  david     28  Houston     Designer
4    Eve     32  Phoenix   Consultant

In [35]:
data.isnull().sum() ## checking for null values in the dataframe, it will return a dataframe of the same shape with boolean values indicating whether the value is null or not

Name        0
 Age        0
 City       0
Position    0
dtype: int64

In [36]:
data.notnull().sum() ## checking for non-null values in the dataframe, it will return a dataframe of the same shape with boolean values indicating whether the value is not null or not

Name        5
 Age        5
 City       5
Position    5
dtype: int64

In [37]:
data.dropna() ## dropping rows with null values from the dataframe, it will return a new dataframe with the rows containing null values removed

      Name    Age           City     Position
0    Alice      30      new york      Manager
1      Bob      25  Los Angeles     Developer
2  charlie      35       chicago      analyst
3     david     28       Houston     Designer
4       Eve     32       Phoenix   Consultant

Dropping the columns which has null values

In [38]:
data.dropna(axis=1)

      Name    Age           City     Position
0    Alice      30      new york      Manager
1      Bob      25  Los Angeles     Developer
2  charlie      35       chicago      analyst
3     david     28       Houston     Designer
4       Eve     32       Phoenix   Consultant

In [39]:
data

      Name    Age           City     Position
0    Alice      30      new york      Manager
1      Bob      25  Los Angeles     Developer
2  charlie      35       chicago      analyst
3     david     28       Houston     Designer
4       Eve     32       Phoenix   Consultant

Instead of dropping just fill the Null Values with actual values

In [40]:
data.fillna(0, inplace=True) ## filling the null values in the dataframe with 0, inplace=True will modify the original dataframe

      Name    Age           City     Position
0    Alice      30      new york      Manager
1      Bob      25  Los Angeles     Developer
2  charlie      35       chicago      analyst
3     david     28       Houston     Designer
4       Eve     32       Phoenix   Consultant